from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('aip650', src, depend = ['PKG_USING_AIP650'], CPPPATH = CPPPATH)

Return('group')
